name: 'Sprint Milestone Action'
description: 'Automatically generate Milestones to manage sprints'
branding:
  icon: 'calendar'
  color: 'green'
inputs:
  sprint-duration:
    description: 'Duration of the sprint expressed in weeks'
    required: false
    default: '1'
outputs:
  milestone-title:
    description: 'Milestone title'
  milestone-number:
    description: 'Milestone number'
  milestone-dueon:
    description: 'Milestone due on'
runs:
  using: 'node12'
  main: 'index.js'