name: 'Sprint Milestone Action'
description: 'Automatically create Milestones to manage sprints'
outputs:
  milestone-id: # id of output
    description: 'ID of the newly created Milestone'
runs:
  using: 'node12'
  main: 'index.js'