name: Sprint Milestone

on: 
  push:
    branches: [ test ]

jobs:
  sprint_milestone:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/sprint-milestone-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sprint-duration: 2 # Default is 1